export const GET_USERS = "GET_USERS"
export const FIND_USERS_BY_NAME = 'FIND_USERS_BY_NAME'
export const FIND_USERS_BY_GENDER = 'FIND_USERS_BY_GENDER'
export const FIND_USERS_BY_AGE = 'FIND_USERS_BY_AGE'
export const GET_USERS_FOR_SEARCH = 'GET_USERS_FOR_SEARCH'